// Header generation for the C/C++ host API.
// cbindgen does not yet handle Rust 2024's #[unsafe(no_mangle)] attribute,
// so we emit the header programmatically here until cbindgen catches up.
// Doc comments are scraped from the /// lines on each extern fn in api.rs,
// so the header stays in sync with the implementation.

use std::collections::HashMap;

fn api_docs(api_rs: &str) -> HashMap<String, Vec<String>> {
    let mut docs: HashMap<String, Vec<String>> = HashMap::new();
    let mut pending: Vec<String> = Vec::new();
    for line in api_rs.lines() {
        let t = line.trim();
        if let Some(d) = t.strip_prefix("///") {
            pending.push(d.trim().to_owned());
        } else if t.starts_with("#[") || t.starts_with("//") {
            // Attributes and plain comments may sit between the doc comment
            // and the fn.
        } else if t.starts_with("pub extern \"C\" fn") || t.starts_with("pub unsafe extern \"C\" fn") {
            if let Some(name) = t.split("fn ").nth(1).and_then(|s| s.split('(').next()) {
                docs.insert(name.trim().to_owned(), std::mem::take(&mut pending));
            }
            pending.clear();
        } else if !t.is_empty() {
            pending.clear();
        }
    }
    docs
}

fn emit_doc(out: &mut String, docs: &HashMap<String, Vec<String>>, name: &str) {
    let Some(lines) = docs.get(name) else { return };
    if lines.is_empty() { return; }
    if lines.len() == 1 {
        out.push_str(&format!("/** {} */\n", lines[0]));
    } else {
        out.push_str(&format!("/** {}\n", lines[0]));
        for l in &lines[1..lines.len() - 1] {
            out.push_str(&format!("    {l}\n"));
        }
        out.push_str(&format!("    {} */\n", lines[lines.len() - 1]));
    }
}

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out = std::path::PathBuf::from(&crate_dir).join("umbra.h");
    let api_rs = std::fs::read_to_string(std::path::Path::new(&crate_dir).join("src/api.rs"))
        .expect("failed to read src/api.rs");
    let docs = api_docs(&api_rs);

    let mut header = String::from(
        r#"#pragma once
/* Auto-generated by build.rs — do not edit. */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct umbra_State umbra_State;

/** Receives the state, reads args via umbra_to*, pushes results via umbra_push*,
    returns the number of results (negative = error). */
typedef int (*umbra_CFunction)(umbra_State *U);

typedef enum {
    UMBRA_OK           = 0,
    UMBRA_ERR_RUNTIME  = 1,
    UMBRA_ERR_SYNTAX   = 2,
} umbra_Status;

"#,
    );

    // (fn name, C declaration) — declarations stay hand-maintained here;
    // the doc comments above each come from api.rs.
    const DECLS: &[(&str, &str)] = &[
        ("umbra_newstate", "umbra_State *umbra_newstate(void);"),
        ("umbra_close", "void         umbra_close(umbra_State *U);"),
        ("umbra_gettop", "int  umbra_gettop(const umbra_State *U);"),
        ("umbra_settop", "void umbra_settop(umbra_State *U, int idx);"),
        ("umbra_pop", "void umbra_pop(umbra_State *U, int n);"),
        ("umbra_pushnil", "void umbra_pushnil(umbra_State *U);"),
        ("umbra_pushnumber", "void umbra_pushnumber(umbra_State *U, double n);"),
        ("umbra_pushinteger", "void umbra_pushinteger(umbra_State *U, int64_t n);"),
        ("umbra_pushboolean", "void umbra_pushboolean(umbra_State *U, int b);"),
        ("umbra_pushstring", "void umbra_pushstring(umbra_State *U, const char *s);"),
        ("umbra_type", "int umbra_type(const umbra_State *U, int idx);"),
        ("umbra_isnumber", "int umbra_isnumber(const umbra_State *U, int idx);"),
        ("umbra_isstring", "int umbra_isstring(const umbra_State *U, int idx);"),
        ("umbra_isnil", "int umbra_isnil(const umbra_State *U, int idx);"),
        ("umbra_isfunction", "int umbra_isfunction(const umbra_State *U, int idx);"),
        ("umbra_tonumber", "double      umbra_tonumber(const umbra_State *U, int idx);"),
        ("umbra_tointeger", "int64_t     umbra_tointeger(const umbra_State *U, int idx);"),
        ("umbra_toboolean", "int         umbra_toboolean(const umbra_State *U, int idx);"),
        ("umbra_tostring", "const char *umbra_tostring(const umbra_State *U, int idx);"),
        ("umbra_getglobal", "void umbra_getglobal(umbra_State *U, const char *name);"),
        ("umbra_setglobal", "void umbra_setglobal(umbra_State *U, const char *name);"),
        ("umbra_dostring", "int umbra_dostring(umbra_State *U, const char *src);"),
        ("umbra_pcall", "int umbra_pcall(umbra_State *U, int nargs, int nres);"),
        ("umbra_register", "void umbra_register(umbra_State *U, const char *name, umbra_CFunction f);"),
        ("umbra_gc_collect", "void   umbra_gc_collect(umbra_State *U);"),
        ("umbra_gc_setstep", "void   umbra_gc_setstep(umbra_State *U, size_t threshold);"),
        ("umbra_set_step_limit", "void   umbra_set_step_limit(umbra_State *U, uint64_t limit);"),
        ("umbra_set_max_objects", "void   umbra_set_max_objects(umbra_State *U, size_t limit);"),
        ("umbra_gc_livecount", "size_t umbra_gc_livecount(const umbra_State *U);"),
    ];

    // Blank lines group the decls the way the old hand-written header did.
    const BREAK_BEFORE: &[&str] = &[
        "umbra_gettop", "umbra_pushnil", "umbra_type", "umbra_tonumber",
        "umbra_getglobal", "umbra_dostring", "umbra_register", "umbra_gc_collect",
    ];

    for (name, decl) in DECLS {
        if BREAK_BEFORE.contains(name) {
            header.push('\n');
        }
        emit_doc(&mut header, &docs, name);
        header.push_str(decl);
        header.push('\n');
    }

    header.push_str(
        r#"
#ifdef __cplusplus
}
#endif
"#,
    );

    std::fs::write(&out, header).expect("failed to write umbra.h");
    println!("cargo:rerun-if-changed=src/api.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
