#pragma once
/* Auto-generated by build.rs — do not edit. */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct umbra_State umbra_State;

/** Receives the state, reads args via umbra_to*, pushes results via umbra_push*,
    returns the number of results (negative = error). */
typedef int (*umbra_CFunction)(umbra_State *U);

typedef enum {
    UMBRA_OK           = 0,
    UMBRA_ERR_RUNTIME  = 1,
    UMBRA_ERR_SYNTAX   = 2,
} umbra_Status;

umbra_State *umbra_newstate(void);
void         umbra_close(umbra_State *U);

int  umbra_gettop(const umbra_State *U);
void umbra_settop(umbra_State *U, int idx);
void umbra_pop(umbra_State *U, int n);

void umbra_pushnil(umbra_State *U);
void umbra_pushnumber(umbra_State *U, double n);
void umbra_pushinteger(umbra_State *U, int64_t n);
void umbra_pushboolean(umbra_State *U, int b);
void umbra_pushstring(umbra_State *U, const char *s);

/** Returns: 0=nil 1=boolean 2=integer 3=float 4=string 5=table 6=function 7=coroutine */
int umbra_type(const umbra_State *U, int idx);
int umbra_isnumber(const umbra_State *U, int idx);
int umbra_isstring(const umbra_State *U, int idx);
int umbra_isnil(const umbra_State *U, int idx);
int umbra_isfunction(const umbra_State *U, int idx);

double      umbra_tonumber(const umbra_State *U, int idx);
int64_t     umbra_tointeger(const umbra_State *U, int idx);
int         umbra_toboolean(const umbra_State *U, int idx);
/** Pointer valid as long as the string value is reachable. */
const char *umbra_tostring(const umbra_State *U, int idx);

void umbra_getglobal(umbra_State *U, const char *name);
void umbra_setglobal(umbra_State *U, const char *name);

/** Compile and run source string. On error pushes the error value
    (message string, or the object passed to error()) and returns non-zero:
    UMBRA_ERR_SYNTAX for parse/compile failures, UMBRA_ERR_RUNTIME otherwise. */
int umbra_dostring(umbra_State *U, const char *src);

/** Protected call: calls function at -(nargs+1) with nargs args.
    On success pushes nres results (-1 = all). On error pushes the error
    value (a string message, or whatever object error() was given).
    Returns 0 on success, non-zero on error. */
int umbra_pcall(umbra_State *U, int nargs, int nres);

/** Register f as a global callable from scripts.
    f receives U with args at stack[1..nargs] and pushes results. */
void umbra_register(umbra_State *U, const char *name, umbra_CFunction f);

/** Run a full GC collection cycle. Call between script executions. */
void   umbra_gc_collect(umbra_State *U);
/** Set the object-count threshold that triggers automatic collection (default 1024). */
void   umbra_gc_setstep(umbra_State *U, size_t threshold);
/** Bounds how many bytecode instructions a script may run before erroring
    out (0 = unlimited); host-only, resets the count. */
void   umbra_set_step_limit(umbra_State *U, uint64_t limit);
/** Host-only hard ceiling on live GC-tracked objects (0 = unlimited); exceeding
    it after a collection attempt is a real error. */
void   umbra_set_max_objects(umbra_State *U, size_t limit);
/** Returns the number of live GC-tracked objects. */
size_t umbra_gc_livecount(const umbra_State *U);

#ifdef __cplusplus
}
#endif
